---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: ss-mysql
  namespace: final
  labels:
    app: mysql
spec:
  replicas: 3
  selector:
    matchLabels:
      app: mysql
  serviceName: svc-mysql
  template:
    metadata:
      labels:
        app: mysql
    spec:
      volumes:
        - name: data-mysql
          persistentVolumeClaim:
            claimName: pvc-mysql
      containers:
      - name: container-mysql
        image: 717693563238.dkr.ecr.us-east-1.amazonaws.com/mysql:v1
        ports:
          - containerPort: 3306
        volumeMounts:
          - name: data-mysql
            mountPath: /var/lib/mysql
        env:
          - name: MYSQL_ROOT_PASSWORD
            valueFrom:
              secretKeyRef:
                name: db-credentials
                key: DBPWD
  volumeClaimTemplates:
    - metadata:
        name: pvc-mysql
      spec:
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: 2Gi
