---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: dp-webapp
  namespace: app
  labels:
    app: employees
spec:
  replicas: 3
  selector:
    matchLabels:
      app: employees
  template:
    metadata:
      labels:
        app: employees
    spec:
      containers:
        - name: container-webapp
          image: 717693563238.dkr.ecr.us-east-1.amazonaws.com/webapp:v1
          ports:
            - containerPort: 80
          envFrom:
            - configMapRef:
                name: app-config
            - secretRef:
                name: db-credentials
